In [2]:
import numpy as np

In [5]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
data[[1, 3]] = data[[3, 1]]
data

array([[77, 77, 15, 68, 47],
       [75, 30, 54, 29, 53],
       [10, 82, 85, 49, 88],
       [45, 26, 68, 66, 91],
       [52, 70, 50, 44, 99]])

In [6]:
data[[1, 3]] = data[[3, 1]]
data

array([[77, 77, 15, 68, 47],
       [45, 26, 68, 66, 91],
       [10, 82, 85, 49, 88],
       [75, 30, 54, 29, 53],
       [52, 70, 50, 44, 99]])

In [7]:
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
normalized_data

array([[0.75280899, 0.75280899, 0.05617978, 0.65168539, 0.41573034],
       [0.39325843, 0.17977528, 0.65168539, 0.62921348, 0.91011236],
       [0.        , 0.80898876, 0.84269663, 0.43820225, 0.87640449],
       [0.73033708, 0.2247191 , 0.49438202, 0.21348315, 0.48314607],
       [0.47191011, 0.6741573 , 0.4494382 , 0.38202247, 1.        ]])

In [17]:
z_score_data = (data - np.mean(data)) / np.std(data)
z_score_data

array([[-0.82151187,  0.08201218,  0.77703068, -1.58603222, -0.16124429],
       [ 1.50680011, -0.36974984,  1.02028716, -0.05699152, -0.43925169],
       [ 0.98553623, -0.40450077, -0.82151187, -1.72503592,  1.57630196],
       [ 0.39477051,  0.11676311,  1.26354363,  1.26354363,  0.15151403],
       [-0.43925169, -1.20377204,  1.36779641, -0.85626279, -1.62078314]])

In [50]:
vector_data = np.ravel(data)

split_arrays = np.array_split(vector_data, 5)
split_arrays = [arr.tolist() for arr in split_arrays]

for sub_array in split_arrays:
    print(f"array ({sub_array})")
    #print(f"array {tuple(list(sub_array))}")
 

array ([76.0, 58.0, 22.0, 89.0, nan])
array ([91.0, 59.0, 42.0, 92.0, nan])
array ([80.0, 15.0, 62.0, 62.0, 47.0])
array ([nan, 51.0, 55.0, 64.0, 3.0])
array ([nan, 7.0, nan, 73.0, 39.0])


In [26]:
vector1 = np.array([3, 5, 6, 7, 8])
vector2 = np.array([2, 4, 6, 8, 10])

dot_product = np.dot(vector1, vector2)
dot_product

198

In [30]:
data = np.array([[6, 5, 4, 4],
                 [5, 7, 7, 8],
                 [0, 10, 8, 12],
                 [13, 14, 25, 16]])

data2 = np.array([[8, 8, 8],
                  [1, 8, 3],
                  [4, 59, 10]])

result = np.dot(data[:3, :3], data2)

result

array([[ 69, 324, 103],
       [ 75, 509, 131],
       [ 42, 552, 110]])

In [31]:
identity_matrix = np.identity(3)

scaled_matrix = identity_matrix * 2

inverse_matrix = np.linalg.inv(scaled_matrix)

inverse_matrix

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

In [33]:
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

data_3x3 = data[:3, :3]

eigenvalues, eigenvectors = np.linalg.eig(data_3x3)
 
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [ 1.92469508e+01 -1.24695077e+00  9.34268442e-17]
Eigenvectors: [[ 0.1937289   0.77433837  0.40824829]
 [ 0.51451855  0.07288936 -0.81649658]
 [ 0.83530819 -0.62855964  0.40824829]]


In [51]:
data = np.array(np.random.randint(1, 100, size=25), dtype=float).reshape(5, 5)

num_elements_to_replace = 5
indices_to_replace = np.random.choice(data.size, size=num_elements_to_replace, replace=False)
data.ravel()[indices_to_replace] = np.nan

missing_value_indices = np.argwhere(np.isnan(data))

print(data)
print(missing_value_indices)

[[63. 18. 90. 44. 34.]
 [nan 62. 14. 95. nan]
 [15. 72. 78. nan 62.]
 [40. 85. 80. nan 53.]
 [nan 26. 89. 60. 41.]]
[[1 0]
 [1 4]
 [2 3]
 [3 3]
 [4 0]]
