In [3]:
import numpy as np 
zeros_vector = np.zeros(10)
zeros_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
my_array = np.zeros(10, dtype=np.float64)
memory_size = my_array.size * my_array.itemsize
memory_size

80

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [6]:
result_vector = np.arange(10, 50)
result_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
input_vector = np.arange(10, 50)
reversed_vector = input_vector[::-1]
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
array_values = np.arange(9)
matrix_3x3 = np.reshape(array_values, (3, 3))
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
non_zero_indices

(array([0, 1, 4]),)

In [10]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
matrix = np.zeros((5, 5)) + np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [12]:
vector = np.linspace(0.1, 0.9, 10)
vector

array([0.1       , 0.18888889, 0.27777778, 0.36666667, 0.45555556,
       0.54444444, 0.63333333, 0.72222222, 0.81111111, 0.9       ])

In [13]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)
sorted_vector

array([0.00582002, 0.07160554, 0.18334603, 0.25249759, 0.5534522 ,
       0.65414407, 0.66506166, 0.79177204, 0.94417378, 0.95901746])

In [14]:
scalar_types = [np.int8, np.int32, np.int64, np.float32, np.float64]

for dtype in scalar_types:
    if np.issubdtype(dtype, np.integer):
        info = np.iinfo(dtype)
        print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")
    else:
        info = np.finfo(dtype)
        print(f"{dtype.__name__}: Min={info.min}, Max={info.max}")

int8: Min=-128, Max=127
int32: Min=-2147483648, Max=2147483647
int64: Min=-9223372036854775808, Max=9223372036854775807
float32: Min=-3.4028234663852886e+38, Max=3.4028234663852886e+38
float64: Min=-1.7976931348623157e+308, Max=1.7976931348623157e+308


In [15]:
float_array = np.array([1.5, 2.7, -3.3, 4.8], dtype=np.float32)
float_array
int_array = float_array.astype(np.int32)
int_array

array([ 1,  2, -3,  4], dtype=int32)

In [16]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)
result_matrix = matrix - row_means
matrix
result_matrix

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [17]:
array_2d = np.array([[4, 9, 1],
                      [2, 5, 3],
                      [7, 6, 8]])

n = 1
sorted_indices = np.argsort(array_2d[:, n])
sorted_array = array_2d[sorted_indices]

array_2d
sorted_array

array([[2, 5, 3],
       [7, 6, 8],
       [4, 9, 1]])

In [18]:
input_array = np.array([[0, 1, 2],
                        [3, 4, 5],
                        [6, 7, 8]])

input_array[[0, 1]] = input_array[[1, 0]]

input_array

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
C = np.array([0, 2, 1, 1, 3])
A = np.repeat(np.arange(len(C)), C)

A
np.bincount(A)

array([0, 2, 1, 1, 3])